# Added for Banish
%tr = (
%tr,
'Banish title' => 'Banish',
'Banish banishIP' => 'Risorsa Banished:',
'Banish configuration' => 'banish la configurazione',
'Banish rule added' => 'la regola ha aggiunto per ',
'Banish rule removed' => 'la regola ha tolto per ',
'Banish rule modified' => 'la regola ha modificato per ',
'Banish rule toggled' => 'la regola ha commutato a ' ,
'Banish sort by ip/network' => 'Specie da Resource',
'Banish sort by remark' => 'Specie dall\'osservazione',
'Banish sort by enabled' => 'Specie dal permesso da',
'Banish click to sort' => 'Scatto alla specie',
'Banish invalid resource' => 'Entri prego in un IP address, in un CIDR, in un MAC address o in un FQDN valido',
'Banish invalid comment' => 'Le virgole sono respinte, usano i punti e virgola preferibilmente',
'Banish Logo' => 'banishLogo.gif',
'Banish Url' => 'http://banish.sidsolutions.net',
'Banish Url Alt' => 'Vada al Web site di Banish',
'Banish Help Url' => 'http://wiki.sidsolutions.net/index.php?title=Banish_L%27Aiuto',
'Banish Help Alt' => 'Vada alla pagina di aiuto di Banish',
'Banish FAQ Url' => 'http://wiki.sidsolutions.net/index.php?title=Italiano_Banish_FAQ',
'Banish FAQ Alt' => 'Vada alla pagina frequentemente chiesta di domande di Banish',
'SID Solutions Url' => 'http://sidsolutions.net',
'SID Solutions Url Alt' => 'Un Progetto Delle Soluzioni di SID',
'Banish Credits title' => 'Banish Gli Accreditamenti',
'Banish Credits' => 'Vada alla pagina di accreditamenti di Banish',
'Banish Credits2' => 'Crediti',
'Banish Home site' => 'Luogo Domestico',
'Banish Help title' => 'Aiuto',
'Banish Developer' => 'Sviluppatore',
'Banish Translations' => 'Traduzioni',
'Banish flag' => 'Bandierina',
'Banish Previous Page' => 'Vada alla pagina precedente',
'Banish Next Page' => 'Vada dopo paginare',
'Banish Filter by' => 'Filtro vicino',
'Banish Filter Title' => 'Filtro da stringa inserita',
'Banish Display Setting' => 'Entrate per la pagina',
'Banish Settings' => ' Banish Regolazioni',
'Banish Viewing Options' => 'Opzioni Di Osservazione',
'Banish display filter applied' => 'Banish filtro dell\'esposizione applicato: ',
'Banish Logs' => 'Log Del Banish',
'Banish hits' => 'Numero totale di connessioni Banish per',
);
# End Banish
