# Added for Banish
%tr = (
%tr,
'Banish title' => ' Banish',
'Banish banishIP' => 'Banished Resource:',
'Banish configuration' => ' Banish configuration',
'Banish rule added' => 'rule added for ',
'Banish rule removed' => 'rule removed for ',
'Banish rule modified' => 'rule modified for ',
'Banish rule toggled' => 'rule toggled to ' ,
'Banish sort by ip/network' => 'Sort by Resource',
'Banish sort by remark' => 'Sort by Remark',
'Banish sort by enabled' => 'Sort by Enabled',
'Banish click to sort' => 'Click to Sort',
'Banish invalid resource' => 'Please enter an valid IP Address, CIDR, MAC Address or FQDN',
'Banish invalid comment' => 'Commas are disallowed, use semicolons instead',
'Banish Logo' => 'banishLogo.gif',
'Banish Url' => 'http://banish.sidsolutions.net',
'Banish Url Alt' => 'Go to the Banish Website',
'Banish Help Url' => 'http://wiki.sidsolutions.net/index.php?title=Banish_Help',
'Banish Help Alt' => 'Go to the Banish Help page',
'Banish FAQ Url' => 'http://wiki.sidsolutions.net/index.php?title=Banish_FAQ',
'Banish FAQ Alt' => 'Go to the Banish Frequently Asked Questions page',
'SID Solutions Url' => 'http://sidsolutions.net',
'SID Solutions Url Alt' => 'A SID Solutions Project',
'Banish Credits title' => 'Banish Credits',
'Banish Credits' => 'Go to the Banish credits page',
'Banish Credits2' => 'Credits',
'Banish Home site' => 'Home Site',
'Banish Help title' => 'Help',
'Banish Developer' => 'Developer',
'Banish Translations' => 'Translations',
'Banish flag' => 'Flag',
'Banish Previous Page' => 'Go to Previous Page',
'Banish Next Page' => 'Go to Next Page',
'Banish Filter by' => 'Filter by',
'Banish Filter Title' => 'Filter by entered string',
'Banish Display Setting' => 'Entries per page',
'Banish Settings' => ' Banish Settings',
'Banish Viewing Options' => 'Viewing Options',
'Banish display filter applied' => 'Banish display filter applied: ',
'Banish Logs' => 'Banish Logs',
'Banish hits' => 'Total number of Banish hits for',
);
# End Banish
