# Added for Banish
%tr = (
%tr,
'Banish title' => ' Banish',
'Banish banishIP' => 'Recurso Banished:',
'Banish configuration' => ' banish la configuración',
'Banish rule added' => 'regla agregó para ',
'Banish rule removed' => 'regla quitada para ',
'Banish rule modified' => 'regla modificada para ',
'Banish rule toggled' => 'regla accionada la palanca a ' ,
'Banish sort by ip/network' => 'Clase de Resource',
'Banish sort by remark' => 'Clase por la observación',
'Banish sort by enabled' => 'Clase por permitido',
'Banish click to sort' => 'Tecleo a la clase',
'Banish invalid resource' => 'Incorpore por favor un IP address, un CIDR, un MAC address o un FQDN válido',
'Banish invalid comment' => 'Las comas se rechazan, utilizan puntos y comas en lugar de otro',
'Banish Logo' => 'banishLogo.gif',
'Banish Url' => 'http://banish.sidsolutions.net',
'Banish Url Alt' => 'Vaya al Web site del Banish',
'Banish Help Url' => 'http://wiki.sidsolutions.net/index.php?title=Banish_La_Ayuda',
'Banish Help Alt' => 'Vaya a la página de la ayuda del Banish',
'Banish FAQ Url' => 'http://wiki.sidsolutions.net/index.php?title=Espa%C3%B1ol_Banish_FAQ',
'Banish FAQ Alt' => 'Vaya a la página con frecuencia pedida de las preguntas del banish',
'SID Solutions Url' => 'http://sidsolutions.net',
'SID Solutions Url Alt' => 'Un Proyecto De las Soluciones de SID',
'Banish Credits title' => 'Banish Los Créditos',
'Banish Credits' => 'Vaya a la página de los créditos del Banish',
'Banish Credits2' => 'Créditos',
'Banish Home site' => 'Sitio Casero Site',
'Banish Help title' => 'Ayuda',
'Banish Developer' => 'Revelador',
'Banish Translations' => 'Traducciones',
'Banish flag' => 'Bandera',
'Banish Previous Page' => 'Vaya a la página anterior',
'Banish Next Page' => 'Vaya a paginar después',
'Banish Filter by' => 'Filtro cerca',
'Banish Filter Title' => 'Filtro por la secuencia entrada',
'Banish Display Setting' => 'Entradas por la página',
'Banish Settings' => ' Banish Ajustes',
'Banish Viewing Options' => 'Opciones De la Visión',
'Banish display filter applied' => 'Banish dfiltro de la exhibición aplicado: ',
'Banish Logs' => 'Registros Del Banish',
'Banish hits' => 'Numero total de "hits" para el Banish.',
);
# End  Banish
