# Added for Banish
%tr = (
%tr,
'Banish title' => ' Banish',
'Banish banishIP' => 'Recurso Banido:',
'Banish configuration' => ' Configurar Banish',
'Banish rule added' => 'regra adicionada para ',
'Banish rule removed' => 'regra removida para ',
'Banish rule modified' => 'regra modificada para ',
'Banish rule toggled' => 'regra activada/desactivada ' ,
'Banish sort by ip/network' => 'Ordenar por recurso',
'Banish sort by remark' => 'Ordenar por Nota',
'Banish sort by enabled' => 'Ordenar por activo',
'Banish click to sort' => 'Clique para ordenar',
'Banish invalid resource' => 'Por favor introduza um endereço de IP, intervalo de IPs, CIDR, endereço MAC ou FQDN (Fully Qualified Domain Name) válido',
'Banish invalid comment' => 'Vírgulas não são permitidas, use ponto e vírgula',
'Banish Logo' => 'banishLogo.gif',
'Banish Url' => 'http://banish.sidsolutions.net',
'Banish Url Alt' => 'Ir para o Website do Banish',
'Banish Help Url' => 'http://wiki.sidsolutions.net/index.php?title=Banish_Ajuda',
'Banish Help Alt' => 'Ir para a página de Ajuda do Banish',
'Banish FAQ Url' => 'http://wiki.sidsolutions.net/index.php?title=Portuguese_Banish_FAQ',
'Banish FAQ Alt' => 'Ir para a página de Perguntas e Respostas Frequentes',
'SID Solutions Url' => 'http://sidsolutions.net',
'SID Solutions Url Alt' => 'Um projecto SID Solutions',
'Banish Credits title' => 'Créditos do Banish',
'Banish Credits' => 'Ir para a página de créditos do Banish',
'Banish Credits2' => 'Creditos',
'Banish Home site' => 'Home Site',
'Banish Help title' => 'Ajuda',
'Banish Developer' => 'Desenvolvimento',
'Banish Translations' => 'Traduções',
'Banish flag' => 'Bandeira',
'Banish Previous Page' => 'Página Anterior',
'Banish Next Page' => 'Próxima Página',
'Banish Filter by' => 'Filtrar por',
'Banish Filter Title' => 'Filtrar por texto introduzido',
'Banish Display Setting' => 'Entradas por página',
'Banish Settings' => ' Definições do Banish',
'Banish Viewing Options' => 'Opções de Visualização',
'Banish display filter applied' => 'Filtro de visualização do Banish aplicado: ',
'Banish Logs' => 'Registros Da Banish',
'Banish hits' => 'Número total de hits do Banish para',
);
# End Banish