# Added for Banish
%tr = (
%tr,
'Banish title' => ' Banish',
'Banish banishIP' => 'Het Middel van Banished:',
'Banish configuration' => ' De configuratie van Banish',
'Banish rule added' => 'regel wordt toegevoegd die voor ',
'Banish rule removed' => 'regel wordt verwijderd die voor ',
'Banish rule modified' => 'regel wordt gewijzigd die voor ',
'Banish rule toggled' => 'regel van een knevel wordt gevoorzid die aan ' ,
'Banish sort by ip/network' => 'Soort door Middel',
'Banish sort by remark' => 'Soort door Opmerking',
'Banish sort by enabled' => 'Soort door Toegelaten',
'Banish click to sort' => 'Klik aan Soort',
'Banish invalid resource' => 'Gelieve te gaan een geldige IP Adres, een CIDR, het Adres van MAC of FQDN in',
'Banish invalid comment' => 'De komma\'s worden in plaats daarvan verboden, gebruiken puntkomma\'s',
'Banish Logo' => 'banishLogo.gif',
'Banish Url' => 'http://banish.sidsolutions.net',
'Banish Url Alt' => 'Ga naar de Website Banish',
'Banish Help Url' => 'http://wiki.sidsolutions.net/index.php?title=Banish_Hulp',
'Banish Help Alt' => 'Ga naar de pagina van de Hulp Banish',
'Banish FAQ Url' => 'http://wiki.sidsolutions.net/index.php?title=Nederland_Banish_FAQ',
'Banish FAQ Alt' => 'Ga naar Banish vroeg vaak de pagina van Vragen',
'SID Solutions Url' => 'http://sidsolutions.net',
'SID Solutions Url Alt' => 'Een SID Project van Oplossingen',
'Banish Credits title' => 'De Kredieten van Banish',
'Banish Credits' => 'Ga naar de Banish kredietenpagina',
'Banish Credits2' => 'Kredieten',
'Banish Home site' => 'De Plaats van het huis',
'Banish Help title' => 'Hulp',
'Banish Developer' => 'Ontwikkelaar',
'Banish Translations' => 'Vertalingen',
'Banish flag' => 'Vlag',
'Banish Previous Page' => 'Ga naar Vorige Pagina',
'Banish Next Page' => 'Ga naar Volgende Pagina',
'Banish Filter by' => 'Filter langs',
'Banish Filter Title' => 'Filter door ingegaan koord',
'Banish Display Setting' => 'Ingangen per pagina',
'Banish Settings' => ' Banish Montages',
'Banish Viewing Options' => 'Het bekijken Opties',
'Banish display filter applied' => 'Banish toegepaste vertoningsfilter: ',
'Banish Logs' => 'Banish Logs',
'Banish hits' => 'Totaal aantal Banish hits voor',
);
# End Banish
