# Added for Banish
%tr = (
%tr,
'Banish title' => ' Banish',
'Banish banishIP' => 'Resource (IP/Bereich/MAC/Domain):',
'Banish configuration' => ' Banish Einstellungen',
'Banish rule added' => 'Regel hinzugefügt: ',
'Banish rule removed' => 'Regel gelöscht: ',
'Banish rule modified' => 'Regel bearbeitet ',
'Banish rule toggled' => 'Regelstatus geändert auf: ' ,
'Banish sort by ip/network' => 'Sortieren nach Resource',
'Banish sort by remark' => 'Sortieren nach Bemerkung',
'Banish sort by enabled' => 'Sortieren nach Status',
'Banish click to sort' => 'Zum Sortieren klicken',
'Banish invalid resource' => 'Bitte eine gültige IP Adresse, CDIR oder FQDN eingeben',
'Banish invalid comment' => 'Ein Komma ist nicht erlaubt, bitte ein Semikolon benutzen',
'Banish Logo' => 'banishLogo.gif',
'Banish Url' => 'http://banish.sidsolutions.net',
'Banish Url Alt' => 'Besuchen Sie die Banish Website',
'Banish Help Url' => 'http://wiki.sidsolutions.net/index.php?title=Banish_Hilfe',
'Banish Help Alt' => 'Besuchen Sie die Online Hilfe',
'Banish FAQ Url' => 'http://wiki.sidsolutions.net/index.php?title=Banish_Deutsches_FAQ',
'Banish FAQ Alt' => 'Besuchen Sie das Banish FAQ',
'SID Solutions Url' => 'http://sidsolutions.net',
'SID Solutions Url Alt' => 'Ein SID Solutions Projekt',
'Banish Credits title' => 'Mitwirkende',
'Banish Credits' => 'Sehen Sie sich an, wer mitgewirkt hat',
'Banish Credits2' => 'Mitwirkende',
'Banish Home site' => 'Banish Homepage',
'Banish Help title' => 'Hilfe',
'Banish Developer' => 'Entwickler',
'Banish Translations' => 'Übersetzer',
'Banish flag' => 'Flag',
'Banish Previous Page' => 'Zurück',
'Banish Next Page' => 'Vor',
'Banish Filter by' => 'Filtern nach',
'Banish Filter Title' => 'Nach Eingabe filtern',
'Banish Display Setting' => 'Einträge pro Seite',
'Banish Settings' => ' Banish Einstellungen',
'Banish Viewing Options' => 'Anzeigeoptionen',
'Banish display filter applied' => 'Aktiver Banish Anzeigefilter: ',
'Banish Logs' => 'Banish-Logdateien',
'Banish hits' => 'Gesamtanzahl der Banish-Treffer für',
);
# End Banish
