# Added for Banish
%tr = (
%tr,
'Banish title' => 'Banish',
'Banish banishIP' => 'Ressource banie:',
'Banish configuration' => ' Banish Configuration',
'Banish rule added' => 'règle ajoutée pour ',
'Banish rule removed' => 'règle retirée pour ',
'Banish rule modified' => 'règle modifiée pour ',
'Banish rule toggled' => 'règle activée pour ' ,
'Banish sort by ip/network' => 'Trier par Resource',
'Banish sort by remark' => 'Trier par Remarque',
'Banish sort by enabled' => 'Trier par Règle active',
'Banish click to sort' => 'Cliquez pour Trier',
'Banish invalid resource' => 'Entrez une adresse IP, CIDR ou FQDN valide',
'Banish invalid comment' => 'Les virgules sont interdites, utilisez plutôt les points-virgules',
'Banish Logo' => 'banishLogo.gif',
'Banish Url' => 'http://banish.sidsolutions.net',
'Banish Url Alt' => 'Visitez le site web de Banish',
'Banish Help Url' => 'http://wiki.sidsolutions.net/index.php?title=Banish_Aide',
'Banish Help Alt' => 'Visitez d\'aide',
'Banish FAQ Url' => 'http://wiki.sidsolutions.net/index.php?title=Banish_FAQ_FR',
'Banish FAQ Alt' => 'Visitez la Foire Aux Questions (FAQ)',
'SID Solutions Url' => 'http://sidsolutions.net',
'SID Solutions Url Alt' => 'Un projet de SID Solutions',
'Banish Credits title' => 'Crédits',
'Banish Credits' => 'Visitez la page des Crédits',
'Banish Credits2' => 'Crédits',
'Banish Home site' => 'Site Web',
'Banish Help title' => 'Aide',
'Banish Developer' => 'Développeur',
'Banish Translations' => 'Traductions',
'Banish flag' => 'Drapeau',
'Banish Previous Page' => 'Allez à la page précédente',
'Banish Next Page' => 'Allez à la page suivante',
'Banish Filter by' => 'Trié par',
'Banish Filter Title' => 'Trié par le texte entré',
'Banish Display Setting' => 'Entrées par page',
'Banish Settings' => ' Banish Settings',
'Banish Viewing Options' => 'Options de Visionnement',
'Banish display filter applied' => 'Banish filtre d\'affichage appliqué: ',
'Banish Logs' => 'Journaux Du Banish',
'Banish hits' => 'Nombre total d\'accès au Banish',
);
# End Banish
